AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  grouch-auth-function

  Sample SAM Template for grouch-auth-function

Resources:
  AuthFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: AuthFunction
      CodeUri: auth/
      Handler: authorizer.lambda_handler
      Runtime: python3.7
      Timeout: 120
      Policies:
        - Statement:
            - Sid: SecretsManager
              Effect: Allow
              Action: secretsmanager:GetSecretValue
              Resource: "*"

Outputs:
  AuthFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt AuthFunction.Arn
    Export:
      Name:
        Fn::Sub: ${AWS::StackName}-AuthFunction
  AuthFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt AuthFunctionRole.Arn
